/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as FellowshipsRouteImport } from './routes/fellowships'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ChipRouteImport } from './routes/chip'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipsRoute = FellowshipsRouteImport.update({
  id: '/fellowships',
  path: '/fellowships',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ChipRoute = ChipRouteImport.update({
  id: '/chip',
  path: '/chip',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chip': typeof ChipRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/fellowships': typeof FellowshipsRoute
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/api/chat': typeof ApiChatRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chip': typeof ChipRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/fellowships': typeof FellowshipsRoute
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/api/chat': typeof ApiChatRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chip': typeof ChipRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/fellowships': typeof FellowshipsRoute
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/api/chat': typeof ApiChatRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chip'
    | '/donate'
    | '/events'
    | '/fellowships'
    | '/leadership'
    | '/news'
    | '/resources'
    | '/admin/posts'
    | '/api/chat'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chip'
    | '/donate'
    | '/events'
    | '/fellowships'
    | '/leadership'
    | '/news'
    | '/resources'
    | '/admin/posts'
    | '/api/chat'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chip'
    | '/donate'
    | '/events'
    | '/fellowships'
    | '/leadership'
    | '/news'
    | '/resources'
    | '/admin/posts'
    | '/api/chat'
    | '/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChipRoute: typeof ChipRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRouteWithChildren
  FellowshipsRoute: typeof FellowshipsRoute
  LeadershipRoute: typeof LeadershipRoute
  NewsRoute: typeof NewsRoute
  ResourcesRoute: typeof ResourcesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowships': {
      id: '/fellowships'
      path: '/fellowships'
      fullPath: '/fellowships'
      preLoaderRoute: typeof FellowshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chip': {
      id: '/chip'
      path: '/chip'
      fullPath: '/chip'
      preLoaderRoute: typeof ChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChipRoute: ChipRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRouteWithChildren,
  FellowshipsRoute: FellowshipsRoute,
  LeadershipRoute: LeadershipRoute,
  NewsRoute: NewsRoute,
  ResourcesRoute: ResourcesRoute,
  AdminPostsRoute: AdminPostsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
